In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("P:/COB.xlsx")

In [3]:
data

Unnamed: 0    Claim ID                              Primary Secondary  \
0              0  1507116439                   QC Life and Health  Medicaid   
1              1  1875426346    BlueCross BlueShield of Tennessee  Medicaid   
2              2  1370677640         Ambetter from Buckeye Health  Medicaid   
3              3  1865326422  Health First Commercial Plans, Inc.  Medicaid   
4              4  1217527469               FirstCare Health Plans  Medicaid   
...          ...         ...                                  ...       ...   
9995        9995  1843233816                    Bright HealthCare  Medicaid   
9996        9996  1303290908  Health First Commercial Plans, Inc.  Medicaid   
9997        9997  1853068479                     Cigna Healthcare  Medicaid   
9998        9998  1707549314               MercyCare Health Plans  Medicaid   
9999        9999  1240749634                  Sanford Health Plan  Medicaid   

     Plan_Type  Billed_Amt  P_Allowed_Amt  Deductible  CoInsurance  Copay  \
0          HMO        4074           1283          58           40    407   
1          EPO        5342           1559          39           40    424   
2          PPO        5339           2848          69           50    107   
3          HMO        5856           1409          56           35    449   
4          EPO        4533           2666          40           20    401   
...        ...         ...            ...         ...          ...    ...   
9995       POS        4767           2602          46           50    271   
9996       POS        4106           1087          52            0    117   
9997       EPO        4558           1831          69           25    181   
9998       PPO        4317           1503          36           35    292   
9999       PPO        4438           1780          46           30    470   

      S_Allowed_Amt  CoInsurance_Amt  Primary_paid  Secondary_paid      OOP  \
0              1568           513.20        304.80            1263  2506.20   
1              1493           623.60        472.40            1020  3849.60   
2              1994          1424.00       1248.00             746  3345.00   
3              2564           493.15        410.85            2153  3292.15   
4              2405           533.20       1691.80             713  2128.20   
...             ...              ...           ...             ...      ...   
9995           3436          1301.00        984.00            2452  1331.00   
9996           2446             0.00        918.00            1528  1660.00   
9997           1294           457.75       1123.25             170  3264.75   
9998           1963           526.05        648.95            1314  2354.05   
9999           1470           534.00        730.00             740  2968.00   

      TPL  Total_Coverage  
0       1         1567.80  
1       1         1492.40  
2       1         1994.00  
3       1         2563.85  
4       1         2404.80  
...   ...             ...  
9995    1         3436.00  
9996    1         2446.00  
9997    1         1293.25  
9998    1         1962.95  
9999    1         1470.00  

[10000 rows x 17 columns]

In [4]:
train_data = data.drop(["Unnamed: 0","Claim ID","Primary","Secondary","Plan_Type","CoInsurance","OOP","Primary_paid","Secondary_paid","TPL"], axis=1)

In [5]:
train_data

Billed_Amt  P_Allowed_Amt  Deductible  Copay  S_Allowed_Amt  \
0           4074           1283          58    407           1568   
1           5342           1559          39    424           1493   
2           5339           2848          69    107           1994   
3           5856           1409          56    449           2564   
4           4533           2666          40    401           2405   
...          ...            ...         ...    ...            ...   
9995        4767           2602          46    271           3436   
9996        4106           1087          52    117           2446   
9997        4558           1831          69    181           1294   
9998        4317           1503          36    292           1963   
9999        4438           1780          46    470           1470   

      CoInsurance_Amt  Total_Coverage  
0              513.20         1567.80  
1              623.60         1492.40  
2             1424.00         1994.00  
3              493.15         2563.85  
4              533.20         2404.80  
...               ...             ...  
9995          1301.00         3436.00  
9996             0.00         2446.00  
9997           457.75         1293.25  
9998           526.05         1962.95  
9999           534.00         1470.00  

[10000 rows x 7 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler    
X = train_data.drop("Total_Coverage", axis=1)
y = train_data["Total_Coverage"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(7000, 6)
(3000, 6)
(7000,)


In [9]:
from sklearn.ensemble import RandomForestRegressor
import statsmodels.formula.api as sm
regressor = RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [10]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('R2 Score:', metrics.r2_score(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 15.370719999999993
R2 Score: 0.9978870722413062
Mean Squared Error: 1327.151627916667
Root Mean Squared Error: 36.430092340216035


In [11]:
import random
billed_amt = np.random.randint(4000,6000,1)
allowed_amt = np.random.randint(1000,3000,1)
coins_list =[0,20,25,30,35,40,45,50]
coinsp = random.choice(coins_list)
coin = (coinsp*allowed_amt)/100
Secondary_allowed_amt = np.random.randint(500,3500,1)
deduc = np.random.randint(30,70,1)
copay=np.random.randint(100,500,1)


new_input = [[billed_amt,allowed_amt,deduc,copay,Secondary_allowed_amt,coin]]
new_input = np.array(new_input)
new_input.shape
new_input = np.reshape(new_input,(new_input.shape[0],new_input.shape[1]))

In [12]:
new_input = sc.transform(new_input)

In [13]:
pred1 = regressor.predict(new_input)

In [14]:
pred1

array([2105.26])

In [15]:
billed_amt

array([4992])

In [16]:
allowed_amt

array([1697])

In [17]:
coin

array([593.95])

In [18]:
Secondary_allowed_amt

array([2105])

In [19]:
deduc

array([49])

In [20]:
copay

array([122])